build-job:
  stage: build
  image: node:18-alpine3.17
  script:
    - yarn
    - yarn build
    - yarn lint

test-job1:
  stage: test
  image: node:18-alpine3.17
  script:
    - yarn
    - yarn test
# deploy-prod:
#   stage: deploy
#   script:
#     - echo "This job deploys something from the $CI_COMMIT_BRANCH branch."
#   environment: production
